# Generated by Django 5.1.7 on 2025-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prince', models.IntegerField()),
                ('image', models.ImageField(upload_to='drinks/pic')),
            ],
        ),
        migrations.CreateModel(
            name='NonvegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prince', models.IntegerField()),
                ('image', models.ImageField(upload_to='nonveg/pic')),
            ],
        ),
        migrations.CreateModel(
            name='SnacksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prince', models.IntegerField()),
                ('image', models.ImageField(upload_to='snacks/pic')),
            ],
        ),
        migrations.CreateModel(
            name='VegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prince', models.IntegerField()),
                ('image', models.ImageField(upload_to='veg/pic')),
            ],
        ),
    ]
