# Generated by Django 5.1.7 on 2025-05-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinksmodel',
            old_name='prince',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='nonvegmodel',
            old_name='prince',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='snacksmodel',
            old_name='prince',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='vegmodel',
            old_name='prince',
            new_name='price',
        ),
    ]
