# Generated by Django 5.1.7 on 2025-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phNumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
